
package com.ibm.jaxws.tutorial.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "AuthorizeUserClientService", targetNamespace = "http://jawxs.ibm.tutorial/jaxws/authorizeuser", wsdlLocation = "http://localhost:8080/OrderProcessWeb/authorizeuser?wsdl")
public class AuthorizeUserClientService
    extends Service
{

    private final static URL ORDERPROCESS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/OrderProcessWeb/authorizeuser?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ORDERPROCESS_WSDL_LOCATION = url;
    }

    public AuthorizeUserClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthorizeUserClientService() {
        super(ORDERPROCESS_WSDL_LOCATION, new QName("http://jawxs.ibm.tutorial/jaxws/authorizeuser", "AuthorizeUser"));
    }

    /**
     * 
     * @return
     *     returns OrderProcessService
     */
    @WebEndpoint(name = "AuthorizeUserPort")
    public AuthorizeUserService getAuthUserPort() {
        return (AuthorizeUserService)super.getPort(new QName("http://jawxs.ibm.tutorial/jaxws/authorizeuser", "AuthorizeUserPort"), AuthorizeUserService.class);
    }

}
