
package com.ibm.jaxws.tutorial.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "OrderProcessService", targetNamespace = "http://jawxs.ibm.tutorial/jaxws/orderprocess")
public interface OrderProcessService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.jaxws.tutorial.service.client.OrderBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processOrder", targetNamespace = "http://jawxs.ibm.tutorial/jaxws/orderprocess", className = "com.ibm.jaxws.tutorial.service.client.ProcessOrder")
    @ResponseWrapper(localName = "processOrderResponse", targetNamespace = "http://jawxs.ibm.tutorial/jaxws/orderprocess", className = "com.ibm.jaxws.tutorial.service.client.ProcessOrderResponse")
    public OrderBean processOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        OrderBean arg0);
    
            
    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns string containing token
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authUser", targetNamespace = "http://jawxs.ibm.tutorial/jaxws/orderprocess")
    @ResponseWrapper(localName = "authUserResponse", targetNamespace = "http://jawxs.ibm.tutorial/jaxws/orderprocess")
    public String authUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);
}
