
package se.kth.flightservice.jaxws.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlightBookingProcess", targetNamespace = "http://jawxs.flightservice.kth.se/jaxws/flightbookingprocess", wsdlLocation = "http://localhost:8080/FlightBookingProcessWeb/flightbookingprocess?wsdl")
public class FlightBookingProcess
    extends Service
{

    private final static URL FLIGHTBOOKINGPROCESS_WSDL_LOCATION;
    private final static WebServiceException FLIGHTBOOKINGPROCESS_EXCEPTION;
    private final static QName FLIGHTBOOKINGPROCESS_QNAME = new QName("http://jawxs.flightservice.kth.se/jaxws/flightbookingprocess", "FlightBookingProcess");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/FlightBookingProcessWeb/flightbookingprocess?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTBOOKINGPROCESS_WSDL_LOCATION = url;
        FLIGHTBOOKINGPROCESS_EXCEPTION = e;
    }

    public FlightBookingProcess() {
        super(__getWsdlLocation(), FLIGHTBOOKINGPROCESS_QNAME);
    }

    public FlightBookingProcess(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTBOOKINGPROCESS_QNAME, features);
    }

    public FlightBookingProcess(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTBOOKINGPROCESS_QNAME);
    }

    public FlightBookingProcess(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTBOOKINGPROCESS_QNAME, features);
    }

    public FlightBookingProcess(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightBookingProcess(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightBookingService
     */
    @WebEndpoint(name = "FlightBookingProcessPort")
    public FlightBookingService getFlightBookingProcessPort() {
        return super.getPort(new QName("http://jawxs.flightservice.kth.se/jaxws/flightbookingprocess", "FlightBookingProcessPort"), FlightBookingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightBookingService
     */
    @WebEndpoint(name = "FlightBookingProcessPort")
    public FlightBookingService getFlightBookingProcessPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jawxs.flightservice.kth.se/jaxws/flightbookingprocess", "FlightBookingProcessPort"), FlightBookingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTBOOKINGPROCESS_EXCEPTION!= null) {
            throw FLIGHTBOOKINGPROCESS_EXCEPTION;
        }
        return FLIGHTBOOKINGPROCESS_WSDL_LOCATION;
    }

}
